//
// Created by 진민성 on 3/22/25.
//

#ifndef MINSINGSIK_ALGORITHM_STUDY_CONTENTS_UNSORTEDTYPE_H
#define MINSINGSIK_ALGORITHM_STUDY_CONTENTS_UNSORTEDTYPE_H


class UnsortedType {

};


#endif //MINSINGSIK_ALGORITHM_STUDY_CONTENTS_UNSORTEDTYPE_H
